### ISSUE TITLE
error

### ISSUE THREAD

**Issue by helpmyserver** [mbax/VanishNoPacket#657]
i use OpGuard and this happens when i type /v:
[17:26:38 ERROR]: Unhandled exception executing command 'v' in plugin VanishNoPa
cket v3.20
org.bukkit.command.CommandException: Unhandled exception executing command 'v' i
n plugin VanishNoPacket v3.20
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spi
got.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spig
ot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) [spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServ
er.java:647) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerCo
nnection.java:1358) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.jav
a:1193) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.jav
a:45) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.jav
a:1) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:
13) [spigot.jar:git-Spigot-de459a2-51263e9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_73]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_73]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.ja
r:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:
732) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:
400) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:
668) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.jav
a:567) [spigot.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.ClassCastException: com.rezzedup.opguard.wrapper.GuardedPla
yer cannot be cast to org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer
        at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.hidePlayer(CraftPl
ayer.java:896) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at org.kitteh.vanish.VanishManager.toggleVanishQuiet(VanishManager.java:
292) ~[?:?]
        at org.kitteh.vanish.VanishManager.toggleVanishQuiet(VanishManager.java:
226) ~[?:?]
        at org.kitteh.vanish.VanishManager.toggleVanish(VanishManager.java:197)
~[?:?]
        at org.kitteh.vanish.VanishCommand.onCommand(VanishCommand.java:45) ~[?:
?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spi
got.jar:git-Spigot-de459a2-51263e9]
        ... 18 more

**Comment by mbax** [comment]
> java.lang.ClassCastException: com.rezzedup.opguard.wrapper.GuardedPlayer cannot be cast to org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer

Here's your problem. I see you've already created a ticket here - https://github.com/RezzedUp/OpGuard/issues/11
