### ISSUE TITLE
Update for 1.12?

### ISSUE THREAD

**Issue by zealousquiche** [mbax/VanishNoPacket#659]
Will VanishNoPacket be getting an update soon to be compatible with Minecraft 1.12?

**Comment by TheMolkaPL** [comment]
Sorry, [Bukkit](https://github.com/Bukkit/Bukkit) is not supporting Minecraft 1.12.

**Comment by mbax** [comment]
@zealousquiche what broke?

**Comment by OasisMaximus** [comment]
On startup, I got this error:

```[07:23:50] [Server thread/INFO]: [VanishNoPacket] Enabling VanishNoPacket v3.19.1
[07:23:50] [Server thread/INFO]: [VanishNoPacket] Colored nametags enabled, but I couldn't find TagAPI
[07:23:50] [Server thread/INFO]: [VanishNoPacket] For awesome colored nametags on vanish, visit
[07:23:50] [Server thread/INFO]: [VanishNoPacket] http://dev.bukkit.org/server-mods/tag/ 
[07:23:50] [Server thread/INFO]: [VanishNoPacket] and download TagAPI.jar
[07:23:50] [Server thread/ERROR]: Error occurred while enabling VanishNoPacket v3.19.1 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server._INVALID_getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at org.kitteh.vanish.VanishPlugin.onEnable(VanishPlugin.java:327) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
```

**Comment by mbax** [comment]
3.20 solves that. Where'd you get 3.19.1?

**Comment by OasisMaximus** [comment]
I honestly have no clue, we haven't had the need to update VNP in a looooong while because it's so stable. Thanks for the quick reply and the fix! Awesome plugin!
