### ISSUE TITLE
Plugin does not work on 1.13

### ISSUE THREAD

**Issue by OllieMartin** [mbax/VanishNoPacket#668]
1.13 introduced a change in the spigot API where a new requirement has been specified for plugin messaging channels. They must be named in lowercase and following the ":" separator notation.

This error prevents the plugin from being used on any 1.13 servers. While this is the only obvious thing wrong with the plugin it is possible that there are more errors caused by 1.13 also. I appreciate this resource hasn't been updated in a long time, but if the messaging channels are the only error then I would hope it would be a quick fix :)

    [15:21:49 INFO]: [VanishNoPacket] Enabling VanishNoPacket v3.20
    [15:21:49 ERROR]: Error occurred while enabling VanishNoPacket v3.20 (Is it up t
    o date?)
    java.lang.IllegalArgumentException: Channel must contain : separator
            at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChann
    el(StandardMessenger.java:474) ~[spigot-1.13.jar:git-Spigot-f68f5a8-4b00823]
            at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginC
    hannel(StandardMessenger.java:209) ~[spigot-1.13.jar:git-Spigot-f68f5a8-4b00823]

            at org.kitteh.vanish.VanishManager.<init>(VanishManager.java:79) ~[?:?]
            at org.kitteh.vanish.VanishPlugin.onEnable(VanishPlugin.java:331) ~[?:?]

            at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[s
    pigot-1.13.jar:git-Spigot-f68f5a8-4b00823]
            at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
    .java:339) [spigot-1.13.jar:git-Spigot-f68f5a8-4b00823]
            at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
    r.java:403) [spigot-1.13.jar:git-Spigot-f68f5a8-4b00823]
            at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.
    java:425) [spigot-1.13.jar:git-Spigot-f68f5a8-4b00823]
            at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer
    .java:339) [spigot-1.13.jar:git-Spigot-f68f5a8-4b00823]
            at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:
    562) [spigot-1.13.jar:git-Spigot-f68f5a8-4b00823]
            at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java
    :524) [spigot-1.13.jar:git-Spigot-f68f5a8-4b00823]
            at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:
    423) [spigot-1.13.jar:git-Spigot-f68f5a8-4b00823]
            at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.ja
    va:288) [spigot-1.13.jar:git-Spigot-f68f5a8-4b00823]
            at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.jav
    a:686) [spigot-1.13.jar:git-Spigot-f68f5a8-4b00823]
            at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]``

**Comment by mbax** [comment]
As a short term fix, comment out that section of code and recompile it?

**Comment by OllieMartin** [comment]
Sure, I was considering just renaming the channels myself as a temporary fix but thought I’d put it here as a formality. 👍

**Comment by OllieMartin** [comment]
I tried to re-compile the code but was plagued with Maven errors. I might have just done it wrong as I am definitely not a Maven expert, but it appears like some of the referenced repos may no longer exist.

I have created a pull request which just re-names the channel name from vanishStatus to vanish:status which will at least fix the error thrown on startup. I'm hoping that the rest of the plugin is still functional on 1.13 as it has stood the test of time so far.

**Comment by lol768** [comment]
>I tried to re-compile the code but was plagued with Maven errors. I might have just done it wrong as I am definitely not a Maven expert, but it appears like some of the referenced repos may no longer exist.

Probably because http://repo.bukkit.org is :coffin:

**Comment by OllieMartin** [comment]
Yeah, I did try to substitute it for spigot to see if it would just magically work, but I was still getting errors from other repos. (Either that or my eclipse setup was badly wrong)

**Comment by OllieMartin** [comment]
Will be trying that ASAP. Thank you :)

**Comment by mbax** [comment]
https://github.com/mbax/VanishNoPacket/commit/703455627dac0f7c4d75123a81811a519b5bab57

[3.20.1](https://dev.bukkit.org/projects/vanish/files/2597365) is compatible with Bukkit 1.7.10, the last Bukkit released before the project died. Coincidentally, I hear it runs on 1.13 versions of forks of the project that exist through ignoring DMCA takedown notices and other US copyright law.

I appreciate the PR <3
