### ISSUE TITLE
When executing the command /vanish nothing happens

### ISSUE THREAD

**Issue by NPCtom** [mbax/VanishNoPacket#676]
When I execute the command /vanish in game or in the console the command is just repeated back to you as well as doing nothing.

**Comment by NPCtom** [comment]
[09:54:53 ERROR]: Error occurred while enabling VanishNoPacket v3.20.1 (Is it up to date?)
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 20 chars (attempted 21 - 'vanishnopacket:status.
	at org.bukkit.plugin.messaging.StandardMessenger.validateChannel(StandardMessenger.java:446) ~[server.jar:git-Bukkit-e60fc34]
	at org.bukkit.plugin.messaging.StandardMessenger.registerIncomingPluginChannel(StandardMessenger.java:208) ~[server.jar:git-Bukkit-e60fc34]
	at org.kitteh.vanish.VanishManager.<init>(VanishManager.java:81) ~[?:?]
	at org.kitteh.vanish.VanishPlugin.onEnable(VanishPlugin.java:331) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Bukkit-e60fc34]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [server.jar:git-Bukkit-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [server.jar:git-Bukkit-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:367) [server.jar:git-Bukkit-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [server.jar:git-Bukkit-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:729) [server.jar:git-Bukkit-e60fc34]
	at org.bukkit.Bukkit.reload(Bukkit.java:534) [server.jar:git-Bukkit-e60fc34]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [server.jar:git-Bukkit-e60fc34]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) [server.jar:git-Bukkit-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:628) [server.jar:git-Bukkit-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:614) [server.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:408) [server.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:372) [server.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:651) [server.jar:git-Bukkit-e60fc34]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:555) [server.jar:git-Bukkit-e60fc34]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by NPCtom** [comment]
It also does this on my 1.7.9 server. But that log is from my CraftBukket 1.12.2 server.

**Comment by mikroskeem** [comment]
Use v3.20 because v3.20.1 simply adds a support for 1.13+, which is not backwards compatible.

**Comment by NPCtom** [comment]
Thank you very much! I just didn't understand why they all had 1.7.9 as their version number :)
