### ISSUE TITLE
I'm stuck in semi-vanish mode

### ISSUE THREAD

**Issue by GuazP** [mbax/VanishNoPacket#689]
Hi,

I stayed in server vanished, then i typed /afk...

I can't now disable vanish due to ''An internal error occured while attempting to preoform this command'', also after relogging I don't have vanish on me. Another issue, other players can hit me, but I can't hit them back...

There is error in the console when I try to type '/v':

```
[11:57:58] [Server thread/ERROR]: Unhandled exception executing command 'v' in plugin VanishNoPacket v3.20.5.3
org.bukkit.command.CommandException: Unhandled exception executing command 'v' in plugin VanishNoPacket v3.20.5.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-505]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:581) ~[?:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:570) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-505]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-505]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2028) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1838) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1791) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1138) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1205) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-505]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-505]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.kitteh.vanish.Commands.VanishCommand.onCommand(VanishCommand.java:54) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-505]
	... 22 more
```

I hope it is enough for you to recreate issue.

**Comment by mbax** [comment]
Hi there! That version number doesn't match up with any version I released, and the exception points to even the location of a file being moved. Where did you get this plugin jar? I'm curious. :)

**Comment by mbax** [comment]
Closing this but I am still interested in knowing where you got this version. :)

**Comment by GuazP** [comment]
Idk, guy who was paid for setup server get it from somewhere.

**Comment by mbax** [comment]
Strange! Thanks for the reply, though :)
