### ISSUE TITLE
[1.17] Unhandled Exception while toggling Vanish

### ISSUE THREAD

**Issue by Wolfst0rm** [mbax/VanishNoPacket#693]
Unhandled Exception while attempting to reenable Vanish on 1.17

Version: CraftBukkit/Spigt 3099-Spigt-c9cea60-e2f5ea3 (MC: 1.17) (Implementing API Version 1.17-R0.1-SNAPSHOT)

```
[Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'v' in plugin VanishNoPacket v3.21.G0.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1943) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1782) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1763) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1124) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1117) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1101) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1030) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.function.Predicate.test(Object)" because "<parameter2>" is null
        at net.minecraft.world.level.World.lambda$3(World.java:813) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.world.level.entity.EntitySection.a(SourceFile:34) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.world.level.entity.EntitySectionStorage.a(SourceFile:123) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.world.level.entity.EntitySectionStorage.a(SourceFile:64) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.world.level.entity.EntitySectionStorage.b(SourceFile:123) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.world.level.entity.LevelEntityGetterAdapter.a(SourceFile:42) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at net.minecraft.world.level.World.getEntities(World.java:812) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at org.bukkit.craftbukkit.v1_17_R1.entity.CraftEntity.getNearbyEntities(CraftEntity.java:531) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        at org.kitteh.vanish.VanishManager.toggleVanishQuiet(VanishManager.java:266) ~[?:?]
        at org.kitteh.vanish.VanishManager.toggleVanishQuiet(VanishManager.java:249) ~[?:?]
        at org.kitteh.vanish.VanishManager.toggleVanish(VanishManager.java:220) ~[?:?]
        at org.kitteh.vanish.VanishCommand.onCommand(VanishCommand.java:61) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:3099-Spigot-c9cea60-e2f5ea3]
        ... 19 more

```

**Comment by mbax** [comment]
From what I understand, this was fixed in Spigot 4 days ago.
